# Generated by Django 5.0.3 on 2024-05-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dailycategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20)),
                ('categoryDescription', models.TextField()),
                ('img', models.ImageField(default='null.jpeg', upload_to='images')),
            ],
        ),
    ]
