# Generated by Django 5.0.3 on 2024-05-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Productcategory', models.CharField(max_length=20)),
                ('img', models.ImageField(default='null.jpeg', upload_to='image')),
            ],
        ),
    ]
