# Generated by Django 5.0.3 on 2024-05-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vegecontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactName', models.CharField(max_length=20)),
                ('ContactNumber', models.IntegerField()),
                ('EmailId', models.EmailField(max_length=254, null=True)),
                ('Message', models.TextField(default='')),
            ],
        ),
    ]
