# Generated by Django 5.0.3 on 2024-05-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruitregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=10)),
                ('EmailId', models.EmailField(max_length=254, null=True)),
                ('Phonenumber', models.IntegerField()),
            ],
        ),
    ]
