# Generated by Django 5.0.3 on 2024-06-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_products'),
        ('Userapp', '0002_fruitregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('cartproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.products')),
                ('cartuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.fruitregister')),
            ],
        ),
    ]
